"""initial schema

Revision ID: 0d70596b7202
Revises: 
Create Date: 2026-09-23 15:46:16.841781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d70596b7202'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_user',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_user_username'), 'admin_user', ['username'], unique=True)
    op.create_table('audit_log',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_id', sa.String(length=32), nullable=True),
    sa.Column('actor_username', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target', sa.String(length=128), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_at'), 'audit_log', ['at'], unique=False)
    op.create_table('booking_lock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('touched_at', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('calendar_credential',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=False),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('calendar_id', sa.String(length=512), nullable=True),
    sa.Column('connected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sync_token', sa.Text(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lead',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('transcript', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_created_at'), 'lead', ['created_at'], unique=False)
    op.create_index(op.f('ix_lead_email'), 'lead', ['email'], unique=False)
    op.create_table('webhook',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('secret', sa.Text(), nullable=False),
    sa.Column('events', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admin_session',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('csrf_token', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['admin_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_admin_session_expires', 'admin_session', ['expires_at'], unique=False)
    op.create_table('content_page',
    sa.Column('slug', sa.String(length=48), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('show_in_nav', sa.Boolean(), nullable=False),
    sa.Column('translations', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['admin_user.id'], ),
    sa.PrimaryKeyConstraint('slug')
    )
    op.create_table('faq_item',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('translations', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['admin_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_source',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('content_type', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('source_ref', sa.String(length=2048), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('chars', sa.Integer(), nullable=False),
    sa.Column('truncated', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['admin_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_source_created_at'), 'knowledge_source', ['created_at'], unique=False)
    op.create_table('service',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('buffer_before_minutes', sa.Integer(), nullable=False),
    sa.Column('buffer_after_minutes', sa.Integer(), nullable=False),
    sa.Column('requires_confirmation', sa.Boolean(), nullable=False),
    sa.Column('payment_required', sa.Boolean(), nullable=False),
    sa.Column('location_type', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('translations', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['admin_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_service_active_position', 'service', ['is_active', 'position'], unique=False)
    op.create_index(op.f('ix_service_slug'), 'service', ['slug'], unique=True)
    op.create_table('site_setting',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('is_secret', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['admin_user.id'], ),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('webhook_delivery',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('webhook_id', sa.String(length=32), nullable=False),
    sa.Column('event', sa.String(length=32), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('attempted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['webhook_id'], ['webhook.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_delivery_attempted_at'), 'webhook_delivery', ['attempted_at'], unique=False)
    op.create_index(op.f('ix_webhook_delivery_webhook_id'), 'webhook_delivery', ['webhook_id'], unique=False)
    op.create_table('appointment',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('time', sa.String(length=5), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=True),
    sa.Column('lang', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=False),
    sa.Column('service', sa.String(length=200), nullable=False),
    sa.Column('service_id', sa.String(length=32), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('external_event_id', sa.String(length=512), nullable=True),
    sa.Column('calendar_drift', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointment_date'), 'appointment', ['date'], unique=False)
    op.create_index('ix_appointment_date_status', 'appointment', ['date', 'status'], unique=False)
    op.create_index(op.f('ix_appointment_email'), 'appointment', ['email'], unique=False)
    op.create_table('availability_rule',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('service_id', sa.String(length=32), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=True),
    sa.Column('date', sa.String(length=10), nullable=True),
    sa.Column('start_time', sa.String(length=5), nullable=True),
    sa.Column('end_time', sa.String(length=5), nullable=True),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_availability_rule_date'), 'availability_rule', ['date'], unique=False)
    op.create_index('ix_availability_rule_service_date', 'availability_rule', ['service_id', 'date'], unique=False)
    op.create_index(op.f('ix_availability_rule_service_id'), 'availability_rule', ['service_id'], unique=False)
    op.create_index('ix_availability_rule_service_weekday', 'availability_rule', ['service_id', 'weekday'], unique=False)
    op.create_table('content_page_version',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('slug', sa.String(length=48), nullable=False),
    sa.Column('translations', sa.JSON(), nullable=False),
    sa.Column('saved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('saved_by', sa.String(length=32), nullable=True),
    sa.Column('saved_by_username', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['slug'], ['content_page.slug'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_page_version_slug'), 'content_page_version', ['slug'], unique=False)
    op.create_table('service_custom_question',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('service_id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_custom_question_service_id'), 'service_custom_question', ['service_id'], unique=False)
    op.create_table('appointment_question_answer',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('appointment_id', sa.String(length=16), nullable=False),
    sa.Column('question_id', sa.String(length=32), nullable=True),
    sa.Column('question_label', sa.String(length=200), nullable=False),
    sa.Column('answer', sa.String(length=2000), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['service_custom_question.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointment_question_answer_appointment_id'), 'appointment_question_answer', ['appointment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_appointment_question_answer_appointment_id'), table_name='appointment_question_answer')
    op.drop_table('appointment_question_answer')
    op.drop_index(op.f('ix_service_custom_question_service_id'), table_name='service_custom_question')
    op.drop_table('service_custom_question')
    op.drop_index(op.f('ix_content_page_version_slug'), table_name='content_page_version')
    op.drop_table('content_page_version')
    op.drop_index('ix_availability_rule_service_weekday', table_name='availability_rule')
    op.drop_index(op.f('ix_availability_rule_service_id'), table_name='availability_rule')
    op.drop_index('ix_availability_rule_service_date', table_name='availability_rule')
    op.drop_index(op.f('ix_availability_rule_date'), table_name='availability_rule')
    op.drop_table('availability_rule')
    op.drop_index(op.f('ix_appointment_email'), table_name='appointment')
    op.drop_index('ix_appointment_date_status', table_name='appointment')
    op.drop_index(op.f('ix_appointment_date'), table_name='appointment')
    op.drop_table('appointment')
    op.drop_index(op.f('ix_webhook_delivery_webhook_id'), table_name='webhook_delivery')
    op.drop_index(op.f('ix_webhook_delivery_attempted_at'), table_name='webhook_delivery')
    op.drop_table('webhook_delivery')
    op.drop_table('site_setting')
    op.drop_index(op.f('ix_service_slug'), table_name='service')
    op.drop_index('ix_service_active_position', table_name='service')
    op.drop_table('service')
    op.drop_index(op.f('ix_knowledge_source_created_at'), table_name='knowledge_source')
    op.drop_table('knowledge_source')
    op.drop_table('faq_item')
    op.drop_table('content_page')
    op.drop_index('ix_admin_session_expires', table_name='admin_session')
    op.drop_table('admin_session')
    op.drop_table('webhook')
    op.drop_index(op.f('ix_lead_email'), table_name='lead')
    op.drop_index(op.f('ix_lead_created_at'), table_name='lead')
    op.drop_table('lead')
    op.drop_table('calendar_credential')
    op.drop_table('booking_lock')
    op.drop_index(op.f('ix_audit_log_at'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_admin_user_username'), table_name='admin_user')
    op.drop_table('admin_user')
    # ### end Alembic commands ###
