"""add product catalog table

Revision ID: 119364b455ba
Revises: 7f95f8e9be31
Create Date: 2026-09-23 19:29:14.232848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '119364b455ba'
down_revision: Union[str, None] = '7f95f8e9be31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['admin_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_product_active_position', 'product', ['is_active', 'position'], unique=False)
    op.create_index(op.f('ix_product_slug'), 'product', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_slug'), table_name='product')
    op.drop_index('ix_product_active_position', table_name='product')
    op.drop_table('product')
    # ### end Alembic commands ###
