"""add calendar_credential.last_sync_error

Revision ID: 4c6fd5ba932f
Revises: 0d70596b7202
Create Date: 2026-09-23 16:24:52.947080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c6fd5ba932f'
down_revision: Union[str, None] = '0d70596b7202'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calendar_credential', sa.Column('last_sync_error', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calendar_credential', 'last_sync_error')
    # ### end Alembic commands ###
