"""add showcase image table

Revision ID: 7f9173861630
Revises: 119364b455ba
Create Date: 2026-09-23 21:36:40.589485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f9173861630'
down_revision: Union[str, None] = '119364b455ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('showcase_image',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('filename', sa.String(length=64), nullable=False),
    sa.Column('caption', sa.String(length=200), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['admin_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_showcase_image_active_position', 'showcase_image', ['is_active', 'position'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_showcase_image_active_position', table_name='showcase_image')
    op.drop_table('showcase_image')
    # ### end Alembic commands ###
