"""remove booking, calendar sync, and services tables

Revision ID: 7f95f8e9be31
Revises: 4c6fd5ba932f
Create Date: 2026-09-23 19:19:28.501582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '7f95f8e9be31'
down_revision: Union[str, None] = '4c6fd5ba932f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_service_custom_question_service_id', table_name='service_custom_question')
    op.drop_table('service_custom_question')
    op.drop_index('ix_appointment_question_answer_appointment_id', table_name='appointment_question_answer')
    op.drop_table('appointment_question_answer')
    op.drop_index('ix_availability_rule_date', table_name='availability_rule')
    op.drop_index('ix_availability_rule_service_date', table_name='availability_rule')
    op.drop_index('ix_availability_rule_service_id', table_name='availability_rule')
    op.drop_index('ix_availability_rule_service_weekday', table_name='availability_rule')
    op.drop_table('availability_rule')
    op.drop_index('ix_appointment_date', table_name='appointment')
    op.drop_index('ix_appointment_date_status', table_name='appointment')
    op.drop_index('ix_appointment_email', table_name='appointment')
    op.drop_table('appointment')
    op.drop_index('ix_service_active_position', table_name='service')
    op.drop_index('ix_service_slug', table_name='service')
    op.drop_table('service')
    op.drop_table('booking_lock')
    op.drop_table('calendar_credential')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_credential',
    sa.Column('id', sa.VARCHAR(length=32), nullable=False),
    sa.Column('provider', sa.VARCHAR(length=32), nullable=False),
    sa.Column('access_token', sa.TEXT(), nullable=False),
    sa.Column('refresh_token', sa.TEXT(), nullable=False),
    sa.Column('token_expires_at', sa.DATETIME(), nullable=False),
    sa.Column('calendar_id', sa.VARCHAR(length=512), nullable=True),
    sa.Column('connected_at', sa.DATETIME(), nullable=False),
    sa.Column('sync_token', sa.TEXT(), nullable=True),
    sa.Column('last_synced_at', sa.DATETIME(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('last_sync_error', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('booking_lock',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('touched_at', sa.VARCHAR(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service',
    sa.Column('id', sa.VARCHAR(length=32), nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), nullable=False),
    sa.Column('slug', sa.VARCHAR(length=64), nullable=False),
    sa.Column('duration_minutes', sa.INTEGER(), nullable=False),
    sa.Column('buffer_before_minutes', sa.INTEGER(), nullable=False),
    sa.Column('buffer_after_minutes', sa.INTEGER(), nullable=False),
    sa.Column('requires_confirmation', sa.BOOLEAN(), nullable=False),
    sa.Column('payment_required', sa.BOOLEAN(), nullable=False),
    sa.Column('location_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('position', sa.INTEGER(), nullable=False),
    sa.Column('translations', sqlite.JSON(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_by', sa.VARCHAR(length=32), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['admin_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_service_slug', 'service', ['slug'], unique=1)
    op.create_index('ix_service_active_position', 'service', ['is_active', 'position'], unique=False)
    op.create_table('appointment',
    sa.Column('id', sa.VARCHAR(length=16), nullable=False),
    sa.Column('date', sa.VARCHAR(length=10), nullable=False),
    sa.Column('time', sa.VARCHAR(length=5), nullable=False),
    sa.Column('timezone', sa.VARCHAR(length=64), nullable=True),
    sa.Column('lang', sa.VARCHAR(length=8), nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), nullable=False),
    sa.Column('email', sa.VARCHAR(length=254), nullable=False),
    sa.Column('phone', sa.VARCHAR(length=40), nullable=False),
    sa.Column('service', sa.VARCHAR(length=200), nullable=False),
    sa.Column('service_id', sa.VARCHAR(length=32), nullable=True),
    sa.Column('notes', sa.VARCHAR(length=1000), nullable=False),
    sa.Column('status', sa.VARCHAR(length=16), nullable=False),
    sa.Column('confirmed_at', sa.DATETIME(), nullable=True),
    sa.Column('external_event_id', sa.VARCHAR(length=512), nullable=True),
    sa.Column('calendar_drift', sa.VARCHAR(length=500), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_appointment_email', 'appointment', ['email'], unique=False)
    op.create_index('ix_appointment_date_status', 'appointment', ['date', 'status'], unique=False)
    op.create_index('ix_appointment_date', 'appointment', ['date'], unique=False)
    op.create_table('availability_rule',
    sa.Column('id', sa.VARCHAR(length=32), nullable=False),
    sa.Column('service_id', sa.VARCHAR(length=32), nullable=True),
    sa.Column('kind', sa.VARCHAR(length=16), nullable=False),
    sa.Column('weekday', sa.INTEGER(), nullable=True),
    sa.Column('date', sa.VARCHAR(length=10), nullable=True),
    sa.Column('start_time', sa.VARCHAR(length=5), nullable=True),
    sa.Column('end_time', sa.VARCHAR(length=5), nullable=True),
    sa.Column('is_closed', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_availability_rule_service_weekday', 'availability_rule', ['service_id', 'weekday'], unique=False)
    op.create_index('ix_availability_rule_service_id', 'availability_rule', ['service_id'], unique=False)
    op.create_index('ix_availability_rule_service_date', 'availability_rule', ['service_id', 'date'], unique=False)
    op.create_index('ix_availability_rule_date', 'availability_rule', ['date'], unique=False)
    op.create_table('appointment_question_answer',
    sa.Column('id', sa.VARCHAR(length=32), nullable=False),
    sa.Column('appointment_id', sa.VARCHAR(length=16), nullable=False),
    sa.Column('question_id', sa.VARCHAR(length=32), nullable=True),
    sa.Column('question_label', sa.VARCHAR(length=200), nullable=False),
    sa.Column('answer', sa.VARCHAR(length=2000), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['service_custom_question.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_appointment_question_answer_appointment_id', 'appointment_question_answer', ['appointment_id'], unique=False)
    op.create_table('service_custom_question',
    sa.Column('id', sa.VARCHAR(length=32), nullable=False),
    sa.Column('service_id', sa.VARCHAR(length=32), nullable=False),
    sa.Column('kind', sa.VARCHAR(length=16), nullable=False),
    sa.Column('label', sa.VARCHAR(length=200), nullable=False),
    sa.Column('required', sa.BOOLEAN(), nullable=False),
    sa.Column('position', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_service_custom_question_service_id', 'service_custom_question', ['service_id'], unique=False)
    # ### end Alembic commands ###
